package:
  name: musicc
  version: "1.0.1"

source:
  fn: MUSiCC-1.0.1.tar.gz
  url: https://pypi.python.org/packages/source/M/MUSiCC/MUSiCC-1.0.1.tar.gz
  md5: 270b23e925c6673643af8610d63070d4

build:
  number: 1
  # Python 3.6 builds for scikit-learn <0.18 are not available on conda-forge
  skip: True  # [py36]

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.6.1
    - scipy >=0.9
    # musicc imports sklearn.utils.ConvergenceWarning which is moved to sklearn.exceptions in scikit-learn 0.18
    - scikit-learn >=0.15.2,<0.18
    - pandas >=0.14

  run:
    - python
    - numpy >=1.6.1
    - scipy >=0.9
    # musicc imports sklearn.utils.ConvergenceWarning which is moved to sklearn.exceptions in scikit-learn 0.18
    - scikit-learn >=0.15.2,<0.18
    - pandas >=0.14

test:
  imports:
    - musicc.core

about:
  home: http://elbo.gs.washington.edu/software_musicc.html
  license: BSD License
  summary: 'MUSICC: A marker genes based framework for metagenomic normalization and accurate profiling of gene abundances in the microbiome.'
