{% set version = "1.38.0" %}
{% set name = "goProfiles" %}
{% set bioc = "3.5" %}

package:
    name: 'bioconductor-{{ name|lower }}'
    version: '{{ version }}'
source:
    md5: 117f1c371b092292fa60c95a47d74271
    url: https://www.bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz
build:
    number: '0'
    rpaths:
        - /usr/local/bin/r
        - lib/R/lib/
        - lib/
requirements:
    build:
        - pixman 0.34.0 ha72d70b_1
        - r-memoise 1.1.0 r3.4.1_0
        - r-rpart 4.1_11 r3.4.1_0
        - openssl 1.0.2l h9d1a558_3
        - r-cluster 2.0.6 r3.4.1_0
        - r-lattice 0.20_35 r3.4.1_0
        - libgcc 7.2.0 h69d50b8_2
        - r-spatial 7.3_11 r3.4.1_0
        - ncurses 5.9 10
        - fontconfig 2.12.1 3
        - libtiff 4.0.8 h90200ff_9
        - bioconductor-go.db 3.4.0 r3.4.1_0
        - r-plogr 0.1_1 r3.4.1_0
        - libiconv 1.14 0
        - gsl 2.2.1 h0743c53_2
        - r-nnet 7.3_12 r3.4.1_0
        - bioconductor-annotationdbi 1.38.0 r3.4.1_0
        - r-mass 7.3_47 r3.4.1_0
        - r-survival 2.41_3 r3.4.1_0
        - r-rcpp 0.12.11 r3.4.1_0
        - r-foreign 0.8_68 r3.4.1_0
        - r-mgcv 1.8_17 r3.4.1_0
        - r-nlme 3.1_131 r3.4.1_0
        - xz 5.2.3 h2bcbf08_1
        - r-digest 0.6.12 r3.4.1_0
        - libstdcxx-ng 7.2.0 h24385c6_1
        - r-dbi 0.6_1 r3.4.1_0
        - libssh2 1.8.0 h8c220ad_2
        - libffi 3.2.1 h4deb6c0_3
        - r-boot 1.3_19 r3.4.1_0
        - jpeg 9b habf39ab_1
        - r 3.4.1 r3.4.1_0
        - libxml2 2.9.4 0
        - ca-certificates 2017.08.26 h1d4fec5_0
        - readline 6.2 2
        - glib 2.50.2 1
        - bioconductor-iranges 2.8.2 r3.4.1_0
        - bioconductor-s4vectors 0.12.2 r3.4.1_0
        - bzip2 1.0.6 h0376d23_1
        - pango 1.40.3 1
        - r-bh 1.62.0_1 r3.4.1_0
        - icu 54.1 0
        - r-base 3.4.1 0
        - cairo 1.14.8 0
        - harfbuzz 0.9.39 2
        - r-kernsmooth 2.23_15 r3.4.1_0
        - freetype 2.5.5 2
        - bioconductor-biocgenerics 0.22.0 r3.4.1_0
        - curl 7.55.1 hcb0b314_2
        - libgcc-ng 7.2.0 hcbc56d2_1
        - r-recommended 3.4.1 r3.4.1_0
        - tk 8.6.7 h5979e9b_1
        - bioconductor-biobase 2.34.0 r3.4.1_0
        - r-codetools 0.2_15 r3.4.1_0
        - pcre 8.39 1
        - r-rsqlite 1.1_2 r3.4.1_0
        - libpng 1.6.32 hda9c8bc_2
        - zlib 1.2.11 hfbfcf68_1
        - r-class 7.3_14 r3.4.1_0
        - r-matrix 1.2_10 r3.4.1_0
    run:
        - bioconductor-biobase
        - bioconductor-annotationdbi
        - bioconductor-go.db
        - r >=2.10
test:
    commands:
        - '$R -e "library(''{{ name }}'')"'
about:
    home: https://www.bioconductor.org/packages/release/bioc/html/{{ name }}.html
    license: GPL-2
    summary: an R package for the statistical analysis of functional profiles
